version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      # Install firebase packages
      - run: sudo npm install -g firebase-tools
      # Deploy
      - run: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
#     - build:
      - deploy:
#         requires:
#           - build
          filters:
            branches:
              only: master
