version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
            - firebase.json

  deploy:
    docker:
      - image: circleci/node:10.9.0

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install firebase packages
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy
          command: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
